version: '2'

services:

  gp-redirect:
    image: "nhsuk/gp-redirect:${GP_REDIRECT_DOCKER_IMAGE_TAG}"
    environment:
      NODE_ENV: production
    labels:
      traefik.enable: stack
      traefik.domain: ${TRAEFIK_DOMAIN}
      traefik.port: 3000
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label_soft: c2s=true
